//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emuher.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfaya Dön.
        /// </summary>
        public static string anasayfayadon {
            get {
                return ResourceManager.GetString("anasayfayadon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araba Detayları.
        /// </summary>
        public static string arabadetayları {
            get {
                return ResourceManager.GetString("arabadetayları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç Satış Platformu.
        /// </summary>
        public static string aracsatisplatformu {
            get {
                return ResourceManager.GetString("aracsatisplatformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string benihatirla {
            get {
                return ResourceManager.GetString("benihatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Ulaşın.
        /// </summary>
        public static string bizeulas {
            get {
                return ResourceManager.GetString("bizeulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Plazalar.
        /// </summary>
        public static string bulunduguplazalar {
            get {
                return ResourceManager.GetString("bulunduguplazalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string detaylar {
            get {
                return ResourceManager.GetString("detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar için tıklayınız.
        /// </summary>
        public static string detaylaricintiklayiniz {
            get {
                return ResourceManager.GetString("detaylaricintiklayiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyata Göre Listele.
        /// </summary>
        public static string fiyatagorelistele {
            get {
                return ResourceManager.GetString("fiyatagorelistele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Merkez Destek.
        /// </summary>
        public static string genelmerkezdestek {
            get {
                return ResourceManager.GetString("genelmerkezdestek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string girisyap {
            get {
                return ResourceManager.GetString("girisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gövde Tipi.
        /// </summary>
        public static string govdetipi {
            get {
                return ResourceManager.GetString("govdetipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string kayitol {
            get {
                return ResourceManager.GetString("kayitol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometre.
        /// </summary>
        public static string kilometre {
            get {
                return ResourceManager.GetString("kilometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string kullaniciadi {
            get {
                return ResourceManager.GetString("kullaniciadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markaya Göre Listele.
        /// </summary>
        public static string markayagorelistele {
            get {
                return ResourceManager.GetString("markayagorelistele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Gücü.
        /// </summary>
        public static string motorgucu {
            get {
                return ResourceManager.GetString("motorgucu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string olustur {
            get {
                return ResourceManager.GetString("olustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazalarımız.
        /// </summary>
        public static string plazalar {
            get {
                return ResourceManager.GetString("plazalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renk Seçenekleri.
        /// </summary>
        public static string renksecenekleri {
            get {
                return ResourceManager.GetString("renksecenekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şanzıman Tipi.
        /// </summary>
        public static string sanzimantipi {
            get {
                return ResourceManager.GetString("sanzimantipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Doğrula.
        /// </summary>
        public static string sifredogrula {
            get {
                return ResourceManager.GetString("sifredogrula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirketimiz 2010 yılında 3 kişi tarafından kurulan otomobil satışı amacıyla kurulmuş bir şirkettir.
        ///Şirketimizin adı 3 ortağın isimlerindeki harflerin birleşiminden gelmektedir.
        ///Şirketimiz Türkiye&apos;nin 4 farklı noktasında işlevini yürütmektedir..
        /// </summary>
        public static string sirketaciklaması {
            get {
                return ResourceManager.GetString("sirketaciklaması", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi.
        /// </summary>
        public static string uyegirisi {
            get {
                return ResourceManager.GetString("uyegirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakıt Tipi.
        /// </summary>
        public static string yakittipi {
            get {
                return ResourceManager.GetString("yakittipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni kullanıcı oluştur.
        /// </summary>
        public static string yenikullanici {
            get {
                return ResourceManager.GetString("yenikullanici", resourceCulture);
            }
        }
    }
}
